name: iOS Build
on:
  push:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: iOS Build
    permissions: write-all
    runs-on: macos-15

    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4.2.3
        with:
          key: cache-build-ios-${{ runner.os }}-v2
          path: |
            $HOME/.hxcpp
            .haxelib/
            export/release/ios/CodenameEngine/haxe/

      - name: Set HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=$HOME/.hxcpp" >> $GITHUB_ENV

      - name: Installing/Updating libraries
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s

      - name: Prebuild hxcpp zlib/zip libraries
        run: |
          haxelib install hxcpp || true
          haxelib run hxcpp rebuild hxcpp_zlib_impl iphoneos || true
          haxelib run hxcpp rebuild zlib_sources iphoneos || true
          haxelib run hxcpp rebuild hxcpp_zip_api iphoneos || true

      - name: Building the game
        run: haxelib run lime build ios -eval -nosign -final

      - name: Clearing already existing cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-ios-${{ runner.os }}-v2") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }

      - name: Making ipa file
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/CodenameEngine.app
          ldid -S../../../CodenameEngine/CodenameEngine.entitlements CodenameEngine
          cd ..
          mkdir Payload
          mv CodenameEngine.app Payload
          zip -r CodenameEngine.ipa Payload

      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: Codename Engine iOS
          path: export/release/ios/build/Release-iphoneos/*.ipa

      - name: Uploading new cache
        uses: actions/cache@v4.2.3
        with:
          key: cache-build-ios-${{ runner.os }}-v2
          path: |
            $HOME/.hxcpp
            .haxelib/
            export/release/ios/CodenameEngine/haxe/
